LBHackney-IT/lbh-etra-front-end

- .circleci/config.yml
What?
- Set up CI pipeline
Why?
- Fast feedback loop of changes.
- Understanding when changes break the build.
> 1 setting up build pipeline

- .circleci/config.yml
- package.json
What:
- Made TestCafe tests run as part of build process
Why:
- So that we know the apps work!
> Run e2e tests on build

- package-lock.json
- package.json
- src/Components/Signature/SignatureCanvas.d.ts
- src/Components/Signature/index.css
- src/Components/Signature/index.stories.tsx
- src/Components/Signature/index.test.tsx
- src/Components/Signature/index.tsx
Created a signature component. Has a built in "Clear" button that can be disabled using props, as well as an OnUpdated callback that can be used to get Base64 string data for the current signature.
Used this package:
https://www.npmjs.com/package/react-signature-canvas
Had to add typescript definitions for the package as currently none exist.
> Created signature component

- README.md
This was changed a little while ago but the Readme was not updated to reflect that.
> Corrected line in Readme that is no longer accurate

- .circleci/config.yml
This should render the cloudfront distribution id
> String interpolation was wrong

- .circleci/config.yml
> Add production gate and deploy stages

- src/Components/LandingPage/index.tsx
- src/TokenLoader.tsx
Fixed an issue I found with how the token loader was working.
> Fix token loader issue

- src/Components/ConfirmLater/index.tsx
- src/Components/ConfirmationPage/index.css
- src/Components/Meeting/index.tsx
- src/Components/ReviewMeeting/index.tsx
What?
-Updated for signoff later flow and setting signoff object as prop.
> Signoff by name

- .env.development
- src/Components/ConfirmLater/index.tsx
- src/Components/ConfirmationPage/index.tsx
Made the work tray links on the confirmation pages configurable in env
> Work tray link

- .env
- .env.development
- src/Components/ConfirmLater/index.tsx
- src/Components/ConfirmationPage/index.tsx
- src/Gateways/MeetingGateway/index.tsx
- src/Utilities/environmentVariables.ts
- src/serviceConfiguration.tsx
Added an environment variable load function that selects which environment variables to load based on the hostname of the app.
> Added support for different environments in .env

- src/Gateways/MeetingGateway/index.tsx
Added content type request header to meeting api requests
> Added content type request header

- README.md
- src/TokenLoader.tsx
Made changes to token loader so that tokens are coming from URL fragment and have different names
> Made necessary changes to how we're loading tokens

- src/Components/LandingPage/index.tsx
- src/Components/SaveMeeting/index.tsx
What?
- Trimmed signature being passed into the saveMeeting. It now does not include `data:image/png;base64,`.
> trim signature

- src/Components/ConfirmationPage/index.tsx
- src/Components/Meeting/index.tsx
- src/Gateways/JWTGateway/index.tsx
Fix ETRA redirect from officer's work  Tray and from react back to officer's work tray
> Fix ETRA redirect from officer's work  Tray and from react back to officer's work tray

- src/JsonFiles/AreaData.json
Added estate name to the location
> Added estatename to the location

- src/JsonFiles/IssueType.json
sort issue type text in json file
> sort issue type text in json file

- src/Components/Meeting/index.tsx
condition added for not rendering the back link if it is an existing meeting
> condition added for not rendering the back link if it is an existing meeting

- src/Components/AddIssue/index.tsx
React does not split into separate line with \n. added code to split the notes to make it more readable.
> Added line breaks in React for displaying multiple notes

- src/Utilities/environmentVariables.ts
changing environment variable for production
> changing environment variable for production

- src/Utilities/environmentVariables.ts
Update Prefix in the environment variable according to url prefixes.
> Update Prefix in the environment variable according to url prefixes.

- src/Components/Meeting/index.tsx
Added code for redirecting from worktray for signoff
> Added code for redirecting from worktray for signoff

- src/Components/LandingPage/index.test.tsx
- src/JsonFiles/AreaData.json
Added Park Side TRa and respective estates and blocks for the TRA
> Added Park Side TRa and respective estates and blocks for the TRA

- public/manifest.json
Minor change to the way browser opens the app to help resolve the offline data syncing issue.
> change display value from standalone to browser

- src/Components/SaveMeeting/index.tsx
Number of attendees must now be at least 1.
> changed attendees logic

- src/Components/Attendees/index.tsx
Added default valued to the Atendees component constructor.
> fixed attendees error

- src/Components/RecordIssues/index.tsx
Increased, top css property of add issue button.
Increased spacing between cancel button.
> Conditional render style

- src/Components/Attendees/index.tsx
> missing bracket error fix

- src/Components/RecordIssues/index.tsx
add spacing between button and text
> amend css style

- src/Components/Attendees/index.stories.tsx
- src/Components/Attendees/index.test.tsx
- src/Components/Attendees/index.tsx
- src/Components/Meeting/index.tsx
Added isComplete prop to attendee component and storiesOf and test.
> Updated Attendee component

- src/Components/Meeting/index.tsx
- src/Components/RecordIssues/index.tsx
Changed conditional rendering of text. Moved text to recordissues component
> amend instructions text

- src/Components/Meeting/index.tsx
- src/Gateways/MeetingGateway/index.tsx
> Check response from API is 200 or "ok".

- src/App.css
- src/Components/ETRA/AddAction/index.tsx
- src/Components/ETRA/ETRAMeeting/index.tsx
- src/Components/ETRA/MeetingSaved/index.css
- src/Components/ETRA/MeetingSaved/index.tsx
- src/Components/ETRA/RecordActions/index.tsx
- src/Components/ETRA/SaveETRAMeeting/index.tsx
https://projects.invisionapp.com/share/RWWD7HSC7BK#/screens/407987320_4a_Save_Meeting_Return_-_Online_-_Is_TRA_Rep_Present
> save ETRA meeting form changes

- src/App.css
- src/Components/ETRA/ETRAMeeting/index.tsx
- src/Components/ETRA/EmailSignOff/index.css
- src/Components/ETRA/EmailSignOff/index.tsx
- src/Components/ETRA/MeetingAttendees/index.css
- src/Components/ETRA/MeetingAttendees/index.stories.tsx
- src/Components/ETRA/MeetingAttendees/index.test.tsx
- src/Components/ETRA/MeetingAttendees/index.tsx
- src/Components/ETRA/MeetingSaved/index.css
- src/Components/ETRA/RecordActions/index.tsx
- src/Components/ETRA/ReviewETRAMeeting/index.tsx
- src/Components/ETRA/SaveETRAMeeting/index.css
- src/Components/ETRA/SignOffETRAMeeting/index.tsx
- src/Components/ETRA/SignatureSignOff/index.css
- src/Components/SaveMeeting/index.css
Created new MeetingAttendees component copied from original Attendees component. 
Removed review-later styling.
Using new lbh frontend styles added to App.css
> Update ETRA Email signoff page.
